name: Compile and Release LaTeX PDF

on:
  push:
    branches:
      - main
    paths:
      - "cv.tex"

jobs:
  build_latex:
    runs-on: pi
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        run: |
          latexmk -lualatex -shell-escape cv.tex
        shell: bash

      - name: Tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const tagName = `release-${context.sha}`;
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagName}`,
              sha: context.sha
            });

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          tag_name: release-${{ github.sha }}
          name: ${{ github.sha }}
          files: cv.pdf
